import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";
import { describe, expect, it } from "vitest";
import { loadNovel } from "../src/index.ts";
import { nodeSource } from "../src/node.ts";
import { relationshipMermaid, snapshots, timelineMermaid } from "../src/snapshots.ts";

const novel = await loadNovel(nodeSource(fileURLToPath(new URL("../../../examples/sample-novel", import.meta.url))));

describe("snapshots", () => {
  it("say the relationship graph in Mermaid, as the app holds it at a scene", () => {
    expect(relationshipMermaid(novel, "sc_0d9wm4")).toBe(
      [
        "flowchart LR",
        '  char_7f3k2q["Ada Varn"]',
        '  char_b3n0vs["Ben Varn"]',
        '  char_m1re1a["Mirela Kost"]',
        '  char_t0ma5h["Tomas Hale"]',
        '  char_7f3k2q ---|"Sibling of"| char_b3n0vs',
        '  char_7f3k2q -.-|"Rivals with"| char_b3n0vs',
        '  char_t0ma5h -->|"Mentor of"| char_7f3k2q',
        "  linkStyle 0 stroke:#2c5d8f,stroke-width:2px",
        "  linkStyle 1 stroke:#a3271d,stroke-width:2px",
        "  linkStyle 2 stroke:#a3271d,stroke-width:2px",
        "",
      ].join("\n"),
    );
  });

  it("put the timeline in Mermaid in story-time order, the flashback noted, colons kept out of labels", () => {
    const t = timelineMermaid(novel);
    expect(t.split("\n").slice(0, 4)).toEqual([
      "timeline",
      "  title Story time",
      "  2 Nov 2009 : The flood of '09 (off page)",
      "  2 Nov 2009, 23∶00 : The Flood (6th in the book, a flashback)",
    ]);
    expect(t).toContain("  Day 3, 18∶30 (3 Mar 2024) : The Betrayal (5th in the book)");
  });

  it("write well-formed SVGs with the diagrams' labels, and an overview embedding them", () => {
    const files = snapshots(novel);
    expect([...files.keys()]).toEqual([
      "diagrams/relationships.svg",
      "diagrams/plotlines.svg",
      "diagrams/presence-characters.svg",
      "diagrams/presence-themes.svg",
      "diagrams/timeline.svg",
      "diagrams/README.md",
    ]);
    for (const [path, text] of files) {
      if (!path.endsWith(".svg")) continue;
      const doc = new new JSDOM("").window.DOMParser().parseFromString(text, "image/svg+xml");
      expect(doc.querySelector("parsererror"), path).toBeNull();
      expect(text, path).toContain("Generated by gh-writer");
    }
    expect(files.get("diagrams/relationships.svg")).toContain(">Allied with<");
    expect(files.get("diagrams/plotlines.svg")).toContain(">Ben&apos;s Debt<".replace("&apos;", "'"));
    expect(files.get("diagrams/timeline.svg")).toContain("6th · flashback");
    const md = files.get("diagrams/README.md")!;
    expect(md).toMatch(/^# Diagrams of The Bridge at Varn\n/);
    for (const svg of ["relationships", "plotlines", "presence-characters", "presence-themes", "timeline"]) expect(md).toContain(`(${svg}.svg)`);
    expect(md.match(/```mermaid\n/g)).toHaveLength(3);
  });

  it("are the same bytes for the same novel", () => {
    expect([...snapshots(novel)]).toEqual([...snapshots(novel)]);
  });
});
