import { DEFAULT_GAP, gaps, graphAt, gridKey, itemTitle, jump, lanesOf, presence, sceneColumns, sortRows, swimlanes, timeline, totals, when, type GraphEdge, type GraphNode, type Presence } from "./diagrams.ts";
import type { Novel, Scene } from "./model.ts";

/*
 * Snapshots: the diagrams as files GitHub shows. Mermaid (which github.com draws) where a diagram can
 * be said in it, SVG for every one, and an overview page embedding them. Written from the same data
 * as the app's views (./diagrams.ts), and deterministic: the same novel gives the same bytes.
 */

/** The app's light palette: SVGs on github.com are shown as they are, on a white page or a dark one, so they carry their own. */
const C = {
  ink: "#1f1d1a",
  muted: "#5f5a52",
  rule: "#ddd6ca",
  paper: "#ffffff",
  panel: "#f1ede5",
  accent: "#2c5d8f",
  accentSoft: "#e9eff5",
  ok: "#2f6b3a",
  warn: "#8a5300",
  warnSoft: "#f6eedf",
  danger: "#a3271d",
} as const;
const TONE: Record<string, string> = { accent: C.accent, ok: C.ok, warn: C.warn, danger: C.danger, ink: C.ink, muted: C.muted };
const FONT = `font-family="system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif"`;
const GENERATED = "Generated by gh-writer from the novel's files: don't edit, it's rewritten when the story changes.";

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const cut = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1)}…` : s);
/** A rough text width at 12px (no fonts to measure with here). */
const width = (s: string, size = 12) => Math.ceil(s.length * size * 0.56);
const svg = (w: number, h: number, title: string, body: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}">\n<!-- ${GENERATED} -->\n<title>${esc(title)}</title>\n<rect width="${w}" height="${h}" fill="${C.paper}"/>\n${body}</svg>\n`;
const ordinal = (n: number) => `${n}${["th", "st", "nd", "rd"][n % 100 >= 11 && n % 100 <= 13 ? 0 : Math.min(n % 10, 4) % 4] ?? "th"}`;

// ——— The relationship graph ———

const firstScene = (novel: Novel) => novel.scenes[0];
const lastScene = (novel: Novel) => novel.scenes.at(-1);

/** Mermaid ids are the entity IDs (letters, digits, underscores); labels are quoted, with quotes escaped. */
const label = (s: string) => `"${s.replace(/"/g, "#quot;")}"`;

/** The relationship graph at a scene as a Mermaid flowchart, styled by relationship type. */
export function relationshipMermaid(novel: Novel, sceneId: string | undefined): string {
  const { nodes, edges } = graphAt(novel, sceneId);
  const lines = ["flowchart LR"];
  for (const n of nodes) lines.push(`  ${n.id}[${label(n.label)}]`);
  const styles: string[] = [];
  edges.forEach((e, i) => {
    const dashed = e.line && e.line !== "solid";
    const arrow = e.directed ? (dashed ? "-.->" : "-->") : dashed ? "-.-" : "---";
    lines.push(`  ${e.source} ${arrow}|${label(e.label)}| ${e.target}`);
    styles.push(`  linkStyle ${i} stroke:${TONE[e.tone ?? "muted"] ?? C.muted},stroke-width:2px`);
  });
  if (!nodes.length) lines.push(`  empty["No characters yet"]`);
  return [...lines, ...styles].join("\n") + "\n";
}

const NODE_W = 150;
const NODE_H = 44;

/** The relationship graph at a scene, drawn as in the app: nodes where they're placed, parallel relationships fanned out. */
export function relationshipSvg(novel: Novel, sceneId: string | undefined, title: string): string {
  const { nodes, edges } = graphAt(novel, sceneId);
  if (!nodes.length) return svg(360, 60, title, `<text x="20" y="36" ${FONT} font-size="13" fill="${C.muted}">No characters yet.</text>\n`);
  const pad = 48;
  const minX = Math.min(...nodes.map((n) => n.x)) - pad;
  const minY = Math.min(...nodes.map((n) => n.y)) - pad - 24;
  const w = Math.max(...nodes.map((n) => n.x)) + NODE_W + pad - minX;
  const h = Math.max(...nodes.map((n) => n.y)) + NODE_H + pad - minY;
  const at = new Map(nodes.map((n) => [n.id, { x: n.x - minX + NODE_W / 2, y: n.y - minY + NODE_H / 2 }]));
  // Relationships between the same two entities, spread around the line between them.
  const groups = new Map<string, GraphEdge[]>();
  for (const e of edges) groups.set([e.source, e.target].sort().join(" "), [...(groups.get([e.source, e.target].sort().join(" ")) ?? []), e]);
  const tones = [...new Set(edges.filter((e) => e.directed).map((e) => e.tone ?? "muted"))];
  let body = `<text x="20" y="28" ${FONT} font-size="14" font-weight="600" fill="${C.ink}">${esc(title)}</text>\n<defs>\n`;
  for (const t of tones) body += `  <marker id="arrow-${t}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="${TONE[t] ?? C.muted}"/></marker>\n`;
  body += "</defs>\n";
  for (const list of groups.values()) {
    list.forEach((e, i) => {
      const a = at.get(e.source)!;
      const b = at.get(e.target)!;
      const offset = (i - (list.length - 1) / 2) * 28 * (e.source < e.target ? 1 : -1);
      const dx = b.x - a.x;
      const dy = b.y - a.y;
      const len = Math.hypot(dx, dy) || 1;
      const cx = (a.x + b.x) / 2 + (-dy / len) * offset * 2;
      const cy = (a.y + b.y) / 2 + (dx / len) * offset * 2;
      const [sx, sy] = edgeOf(a, cx, cy);
      const [tx, ty] = edgeOf(b, cx, cy);
      const colour = TONE[e.tone ?? "muted"] ?? C.muted;
      const dash = e.line === "dashed" ? ` stroke-dasharray="6 4"` : e.line === "dotted" ? ` stroke-dasharray="2 4"` : "";
      const marker = e.directed ? ` marker-end="url(#arrow-${e.tone ?? "muted"})"` : "";
      body += `<path d="M${r(sx)},${r(sy)} Q${r(cx)},${r(cy)} ${r(tx)},${r(ty)}" fill="none" stroke="${colour}" stroke-width="1.75"${dash}${marker}/>\n`;
      const lx = 0.25 * sx + 0.5 * cx + 0.25 * tx;
      const ly = 0.25 * sy + 0.5 * cy + 0.25 * ty;
      const lw = width(e.label, 11) + 10;
      body += `<rect x="${r(lx - lw / 2)}" y="${r(ly - 9)}" width="${lw}" height="18" rx="3" fill="${C.paper}"/><text x="${r(lx)}" y="${r(ly + 4)}" text-anchor="middle" ${FONT} font-size="11" fill="${C.ink}">${esc(e.label)}</text>\n`;
    });
  }
  for (const n of nodes) body += node(n, at.get(n.id)!);
  return svg(Math.ceil(w), Math.ceil(h), title, body);
}

const r = (n: number) => Math.round(n * 10) / 10;

/** Where the line from a node's centre toward (x, y) leaves its box. */
function edgeOf(c: { x: number; y: number }, x: number, y: number): [number, number] {
  const dx = x - c.x;
  const dy = y - c.y;
  if (!dx && !dy) return [c.x, c.y];
  const s = Math.min(Math.abs((NODE_W / 2 + 3) / (dx || 1e-9)), Math.abs((NODE_H / 2 + 3) / (dy || 1e-9)));
  return [c.x + dx * s, c.y + dy * s];
}

function node(n: GraphNode, c: { x: number; y: number }): string {
  return (
    `<rect x="${r(c.x - NODE_W / 2)}" y="${r(c.y - NODE_H / 2)}" width="${NODE_W}" height="${NODE_H}" rx="8" fill="${C.paper}" stroke="${C.rule}"/>\n` +
    `<text x="${r(c.x)}" y="${r(c.y - 2)}" text-anchor="middle" ${FONT} font-size="13" font-weight="600" fill="${C.ink}">${esc(cut(n.label, 20))}</text>\n` +
    `<text x="${r(c.x)}" y="${r(c.y + 13)}" text-anchor="middle" ${FONT} font-size="10.5" fill="${C.muted}">${esc(n.type)}</text>\n`
  );
}

// ——— Grids: plotline swimlanes and presence ———

interface Dot {
  r: number;
  style: "filled" | "hollow" | "dashed";
  ring?: boolean;
}

interface Grid {
  title: string;
  rows: { id: string; name: string; aside?: string }[];
  scenes: Scene[];
  dot: (row: string, scene: string) => Dot | undefined;
  shaded: Set<string>;
}

const COL = 34;
const ROW = 32;
const HEADER = 170;

/** Rows of entries against one column per scene, under chapter and part headers, with dots and shaded absences. */
function gridSvg(novel: Novel, g: Grid): string {
  const { chapters, parts } = sceneColumns(novel, g.scenes);
  const top = 40;
  const partH = parts.length ? 20 : 0;
  const chapterH = 22;
  const titlesH = 130;
  const headY = top + partH + chapterH;
  const bodyY = headY + titlesH;
  const w = HEADER + g.scenes.length * COL + 20;
  const h = bodyY + g.rows.length * ROW + 20;
  let b = `<text x="20" y="26" ${FONT} font-size="14" font-weight="600" fill="${C.ink}">${esc(g.title)}</text>\n`;
  let x = HEADER;
  for (const p of parts) {
    b += `<text x="${x + 4}" y="${top + 14}" ${FONT} font-size="10" font-weight="600" letter-spacing="0.5" fill="${C.muted}">${esc(cut(p.part.title.toUpperCase(), Math.floor((p.span * COL) / 6.5)))}</text>\n<line x1="${x}" y1="${top}" x2="${x}" y2="${bodyY + g.rows.length * ROW}" stroke="${C.rule}"/>\n`;
    x += p.span * COL;
  }
  x = HEADER;
  for (const c of chapters) {
    b += `<text x="${x + 4}" y="${top + partH + 15}" ${FONT} font-size="11.5" font-weight="600" fill="${C.ink}">${esc(cut(c.title, Math.floor((c.span * COL) / 6.5)))}</text>\n<line x1="${x}" y1="${top + partH}" x2="${x}" y2="${bodyY + g.rows.length * ROW}" stroke="${C.rule}"/>\n`;
    x += c.span * COL;
  }
  g.scenes.forEach((s, i) => {
    const cx = HEADER + i * COL + COL / 2;
    b += `<text transform="translate(${cx + 4},${headY + 6}) rotate(90)" ${FONT} font-size="11" fill="${C.ink}">${esc(cut(s.title, 20))}</text>\n`;
  });
  g.rows.forEach((row, k) => {
    const y = bodyY + k * ROW;
    b += `<line x1="20" y1="${y}" x2="${w - 20}" y2="${y}" stroke="${C.rule}"/>\n`;
    b += `<text x="20" y="${y + 20}" ${FONT} font-size="12.5" font-weight="600" fill="${C.ink}">${esc(cut(row.name, 18))}${row.aside ? `<tspan font-weight="400" fill="${C.muted}"> ${esc(row.aside)}</tspan>` : ""}</text>\n`;
    g.scenes.forEach((s, i) => {
      const cx = HEADER + i * COL + COL / 2;
      const cy = y + ROW / 2;
      if (g.shaded.has(gridKey(row.id, s.id))) b += `<rect x="${HEADER + i * COL}" y="${y}" width="${COL}" height="${ROW}" fill="${C.warnSoft}"/>\n`;
      b += `<line x1="${HEADER + i * COL}" y1="${cy}" x2="${HEADER + (i + 1) * COL}" y2="${cy}" stroke="${C.rule}"/>\n`;
      const d = g.dot(row.id, s.id);
      if (!d) return;
      const fill = d.style === "filled" ? C.accent : d.style === "hollow" ? C.accentSoft : C.paper;
      const dash = d.style === "dashed" ? ` stroke-dasharray="2 2"` : "";
      b += `<circle cx="${cx}" cy="${cy}" r="${d.r}" fill="${fill}" stroke="${C.accent}" stroke-width="1.25"${dash}/>\n`;
      if (d.ring) b += `<circle cx="${cx}" cy="${cy}" r="${d.r + 3}" fill="none" stroke="${C.accent}" stroke-width="1.25"/>\n`;
    });
  });
  b += `<line x1="20" y1="${bodyY + g.rows.length * ROW}" x2="${w - 20}" y2="${bodyY + g.rows.length * ROW}" stroke="${C.rule}"/>\n`;
  return svg(w, h, g.title, b);
}

/** Absences (or quiet plotlines) as shaded cells. */
function shadedOf(list: { lane: string; from: string; to: string }[], scenes: Scene[]): Set<string> {
  const ids = scenes.map((s) => s.id);
  const out = new Set<string>();
  for (const g of list) for (const id of ids.slice(ids.indexOf(g.from), ids.indexOf(g.to) + 1)) out.add(gridKey(g.lane, id));
  return out;
}

/** The plotline swimlanes: a large dot for a major beat, a small one for a minor; shaded, a plotline gone quiet past the novel's threshold. */
export function plotlinesSvg(novel: Novel): string {
  const s = swimlanes(novel);
  const threshold = novel.config?.plotline_gap ?? DEFAULT_GAP;
  return gridSvg(novel, {
    title: "Plotlines by scene",
    rows: s.lanes.map((l) => ({ id: l.id, name: l.name })),
    scenes: s.scenes,
    dot: (row, scene) => {
      const m = s.marks.get(gridKey(row, scene));
      return m && (m.weight === "major" ? { r: 7, style: "filled" } : { r: 5, style: "hollow" });
    },
    shaded: shadedOf(gaps(s, threshold), s.scenes),
  });
}

const dotOf = (p: Presence): Dot =>
  !p.listed ? { r: 5, style: "dashed" } : p.strength !== undefined ? { r: 3 + p.strength * 1.6, style: "filled" } : { r: 6, style: "filled", ...(p.pov ? { ring: true } : {}) };

/** Presence of a type's entries across the scenes, by first appearance: filled where listed, ringed for the point of view, dashed where only mentioned. */
export function presenceSvg(novel: Novel, type: string, title: string): string {
  const m = presence(novel, type);
  const count = totals(m);
  const rows = sortRows(m, "first");
  return gridSvg(novel, {
    title,
    rows: rows.map((r) => ({ id: r.id, name: r.name, aside: String(count.get(r.id) ?? 0) })),
    scenes: m.scenes,
    dot: (row, scene) => {
      const p = m.marks.get(gridKey(row, scene));
      return p && dotOf(p);
    },
    shaded: shadedOf(gaps({ lanes: rows, scenes: m.scenes, marks: m.marks, words: m.words }, DEFAULT_GAP), m.scenes),
  });
}

// ——— The timeline ———

/** Mermaid's timeline uses ":" between a period and its events, so a colon in a label is written as "∶". */
const tl = (s: string) => s.replace(/:/g, "∶").replace(/#/g, "No.");

/** The timeline in Mermaid: each moment in story time with what happens then, the book's position and flashbacks noted. */
export function timelineMermaid(novel: Novel): string {
  const t = timeline(novel, "pov");
  const lines = ["timeline", "  title Story time"];
  let period = "";
  let events: string[] = [];
  const flush = () => period && lines.push(`  ${tl(period)} : ${events.map(tl).join(" : ")}`);
  for (const item of t.items) {
    const what =
      item.kind === "scene"
        ? `${item.scene.title} (${ordinal(novel.scenes.indexOf(item.scene) + 1)} in the book${t.flashbacks.has(item.scene.id) ? ", a flashback" : ""})`
        : `${item.event.title} (off page)`;
    const at = when(item);
    if (at === period) events.push(what);
    else {
      flush();
      period = at;
      events = [what];
    }
  }
  flush();
  if (!t.items.length) lines.push("  No times yet : Give scenes a time in their details");
  return lines.join("\n") + "\n";
}

const SLOT = 136;
const LANE_H = 54;

/** The timeline as drawn in the app: story time in lanes by point of view, joined to reading order below. */
export function timelineSvg(novel: Novel): string {
  const t = timeline(novel, "pov");
  const title = "The book in story time, and in reading order";
  if (!t.items.length) return svg(420, 60, title, `<text x="20" y="36" ${FONT} font-size="13" fill="${C.muted}">No scene or event has a time yet.</text>\n`);
  const head = 150;
  const top = 44;
  const axisH = 50;
  const lanesY = top + axisH;
  const linksY = lanesY + t.lanes.length * LANE_H;
  const linksH = 70;
  const readY = linksY + linksH;
  const reading = novel.scenes.filter((s) => t.storyRank.has(s.id));
  const w = head + t.items.length * SLOT + 20;
  const readSlot = (t.items.length * SLOT) / Math.max(1, reading.length);
  const h = readY + 34 + 16;
  let b = `<text x="20" y="26" ${FONT} font-size="14" font-weight="600" fill="${C.ink}">${esc(title)}</text>\n`;
  b += `<text x="20" y="${top + 26}" ${FONT} font-size="11" fill="${C.muted}">Story time</text>\n`;
  t.items.forEach((item, i) => {
    const x = head + i * SLOT;
    b += `<line x1="${x}" y1="${top}" x2="${x}" y2="${linksY}" stroke="${C.rule}"/>\n`;
    // "Day 3, 18:30 (3 Mar 2024)": the day on one line, the date under it.
    const [first, second] = when(item).split(" (");
    b += `<text x="${x + 6}" y="${top + (second ? 27 : 32)}" ${FONT} font-size="10.5" fill="${C.muted}">${esc(cut(first!, 22))}${second ? `<tspan x="${x + 6}" dy="12">${esc(cut(second.replace(/\)$/, ""), 22))}</tspan>` : ""}</text>\n`;
    const prev = t.items[i - 1];
    if (prev) {
      const gap = jump(prev.at, item.at);
      if (gap && gap !== "same time") b += `<rect x="${x - width(gap, 10) / 2 - 4}" y="${top + 2}" width="${width(gap, 10) + 8}" height="15" rx="3" fill="${C.accentSoft}"/><text x="${x}" y="${top + 13}" text-anchor="middle" ${FONT} font-size="10" fill="${C.ink}">${esc(gap)}</text>\n`;
    }
  });
  t.lanes.forEach((lane, k) => {
    const y = lanesY + k * LANE_H;
    b += `<line x1="20" y1="${y}" x2="${w - 20}" y2="${y}" stroke="${C.rule}"/>\n<text x="20" y="${y + 30}" ${FONT} font-size="12.5" font-weight="600" fill="${C.ink}">${esc(cut(lane.name, 18))}</text>\n`;
    t.items.forEach((item, i) => {
      if (!lanesOf(item, "pov").includes(lane.id)) return;
      const x = head + i * SLOT + 6;
      const flashback = item.kind === "scene" && t.flashbacks.has(item.scene.id);
      const event = item.kind === "event";
      b += `<rect x="${x}" y="${y + 7}" width="${SLOT - 12}" height="40" rx="6" fill="${event ? C.paper : C.paper}" stroke="${flashback ? C.warn : event ? C.muted : C.rule}" stroke-width="${flashback ? 2 : 1}"${event ? ` stroke-dasharray="4 3"` : ""}/>\n`;
      b += `<text x="${x + 8}" y="${y + 24}" ${FONT} font-size="11.5" font-weight="600"${event ? ` font-style="italic"` : ""} fill="${C.ink}">${esc(cut(itemTitle(item), 19))}</text>\n`;
      const sub = item.kind === "scene" ? (flashback ? `${ordinal(novel.scenes.indexOf(item.scene) + 1)} · flashback` : `${ordinal(novel.scenes.indexOf(item.scene) + 1)} in the book`) : "off page";
      b += `<text x="${x + 8}" y="${y + 39}" ${FONT} font-size="10" fill="${flashback ? C.warn : C.muted}">${esc(sub)}</text>\n`;
    });
  });
  b += `<line x1="20" y1="${linksY}" x2="${w - 20}" y2="${linksY}" stroke="${C.rule}"/>\n`;
  reading.forEach((scene, rIdx) => {
    const k = t.storyRank.get(scene.id)!;
    const flashback = t.flashbacks.has(scene.id);
    b += `<line x1="${head + k * SLOT + SLOT / 2}" y1="${linksY}" x2="${r(head + rIdx * readSlot + readSlot / 2)}" y2="${readY}" stroke="${flashback ? C.warn : C.rule}" stroke-width="${flashback ? 2.5 : 1.5}"/>\n`;
    b += `<text x="${r(head + rIdx * readSlot + 4)}" y="${readY + 20}" ${FONT} font-size="10.5" fill="${flashback ? C.warn : C.ink}">${esc(cut(`${rIdx + 1}. ${scene.title}`, Math.floor(readSlot / 6.2)))}</text>\n`;
  });
  b += `<line x1="20" y1="${readY}" x2="${w - 20}" y2="${readY}" stroke="${C.rule}"/>\n<text x="20" y="${readY + 20}" ${FONT} font-size="11" fill="${C.muted}">Reading order</text>\n`;
  return svg(w, h, title, b);
}

// ——— The overview ———

/** Every snapshot file, by path from the novel's root: the SVGs and diagrams/README.md, which embeds them. */
export function snapshots(novel: Novel): Map<string, string> {
  const title = novel.config?.title ?? "the novel";
  const first = firstScene(novel);
  const last = lastScene(novel);
  const files = new Map<string, string>();
  files.set("diagrams/relationships.svg", relationshipSvg(novel, last?.id, last ? `Relationships at the end of the book (“${last.title}”)` : "Relationships"));
  files.set("diagrams/plotlines.svg", plotlinesSvg(novel));
  const hasType = (key: string) => novel.entityTypes.some((t) => t.key === key) && novel.entities.some((e) => e.type === key);
  if (hasType("character")) files.set("diagrams/presence-characters.svg", presenceSvg(novel, "character", "Characters by scene"));
  if (hasType("theme")) files.set("diagrams/presence-themes.svg", presenceSvg(novel, "theme", "Themes by scene"));
  files.set("diagrams/timeline.svg", timelineSvg(novel));
  const fence = (s: string) => "```mermaid\n" + s + "```\n";
  const md = [
    `# Diagrams of ${title}`,
    "",
    `_${GENERATED} Open the novel in gh-writer for the live, editable views._`,
    "",
    "## Relationships",
    "",
    ...(first && first.id !== last?.id ? [`At the start of the book (“${first.title}”):`, "", fence(relationshipMermaid(novel, first.id))] : []),
    last ? `At the end of the book (“${last.title}”):` : "From the start:",
    "",
    fence(relationshipMermaid(novel, last?.id)),
    "As drawn in gh-writer, where the nodes are placed by hand:",
    "",
    "![Relationships at the end of the book](relationships.svg)",
    "",
    "## Plotlines",
    "",
    "Each column is a scene, in reading order: a large dot is a major beat, a small one a minor beat. Shaded: a plotline gone quiet for longer than the novel's threshold.",
    "",
    "![Plotlines by scene](plotlines.svg)",
    "",
    "## Presence",
    "",
    "Filled where the scene lists them (ringed: its point of view; for themes, larger for a stronger one), dashed where the prose only mentions them. The number by each name is how many scenes it's in; shaded, an absence of more than three scenes.",
    "",
    ...(files.has("diagrams/presence-characters.svg") ? ["![Characters by scene](presence-characters.svg)", ""] : []),
    ...(files.has("diagrams/presence-themes.svg") ? ["![Themes by scene](presence-themes.svg)", ""] : []),
    "## Timeline",
    "",
    "When things happen in the story, next to where they come in the book.",
    "",
    fence(timelineMermaid(novel)),
    "![The book in story time, and in reading order](timeline.svg)",
    "",
  ];
  files.set("diagrams/README.md", md.join("\n"));
  return files;
}


